# Generated by Django 5.2.8 on 2025-11-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(help_text='Enter Student Name', max_length=20)),
                ('phone_number', models.IntegerField(help_text='Enter Phone Number')),
                ('address', models.CharField(help_text='Enter Address', max_length=50)),
                ('order_no', models.IntegerField(help_text='Enter the Order Number')),
            ],
        ),
    ]
